apiVersion: v1
kind: Pod
metadata:
  name: convergence-tracker-{{.Replica}}
  labels:
    app: convergence-tracker
spec:
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: convergence-tracker
  restartPolicy: Never
  hostNetwork: true
  containers:
    - name: tracker
      # image built with the ./policy-tracker/Dockerfile
      image: gcr.io/unique-caldron-775/netpol-benchmark/convergence:latest
      securityContext:
        privileged: true
      command: [ "/bin/bash", "-c", "python policy-tracker.py"]
      imagePullPolicy: Always
      env:
        - name: CONVERGENCE_PERIOD
          value: "{{.convergence_period}}"
        - name: CONVERGENCE_TIMEOUT
          value: "{{.convergence_timeout}}"
        - name: ES_SERVER
          value: {{.es_server}}
        - name: ES_INDEX_NETPOL
          value: {{.es_index}}
        - name: UUID
          value: {{.UUID}}
        - name: METADATA
          value: "{{.metadata}}"
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
