apiVersion: v1
kind: Pod
metadata:
  name: convergence-tracker-{{.Replica}}
  labels:
    app: convergence-tracker
spec:
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: convergence-tracker
  volumes:
    - name: openvswitch
      hostPath:
        path: /var/run/openvswitch
    - name: ovn-ic
      hostPath:
        path: /var/run/ovn-ic/
    - name: ovn-kubernetes
      hostPath:
        path: /var/run/ovn-kubernetes
    - name: host-var-log-ovs
      hostPath:
        path: /var/log/openvswitch
    - name: pod-logs
      hostPath:
        path: /var/log/pods
  restartPolicy: Never
  containers:
    - name: tracker
      # image built with the ./openflow-tracker/Dockerfile
      image: quay.io/npinaeva/netpol-scale:openshift
      securityContext:
        privileged: true
      command: [ "/bin/bash", "-c", "python openflow-tracker.py"]
      imagePullPolicy: Always
      volumeMounts:
        - name: openvswitch
          mountPath: /var/run/openvswitch
        - name: host-var-log-ovs
          mountPath: /var/log/openvswitch
        - name: ovn-ic
          mountPath: /var/run/ovn
        - name: pod-logs
          mountPath: /var/log/pods
      env:
        - name: THRESHOLD
          value: "{{.threshold}}"
        - name: ES_SERVER
          value: {{.es_server}}
        - name: ES_INDEX_NETPOL
          value: {{.es_index}}
        - name: UUID
          value: {{.UUID}}
        - name: METADATA
          value: "{{.metadata}}"
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
