# pullrequest.yml
name: Lint Workflow
on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        ref: ${{ github.event.pull_request.head.sha }}
        persist-credentials: false

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Run pre-commit hooks
      run: pre-commit run --all-files
